import fs from "node:fs";
import path from "node:path";
import { adjudicate } from "../lib/matrix";
import { Jurisdiction } from "../lib/corpus";
import { loadBenchmark } from "../lib/benchmarkIntegrity";

const OUT = path.resolve("data/sample_gallery.json");

interface GalleryDef {
  case_id: string;
  item_id: string;
  jurisdiction: Jurisdiction;
  note: string;
}

const defs: GalleryDef[] = [
  { case_id: "IN-01", item_id: "B05", jurisdiction: "india", note: "banana peels — kitchen waste, confident Tier 1" },
  { case_id: "IN-02", item_id: "B09", jurisdiction: "india", note: "grease-tainted pizza box — clarify before judging" },
  { case_id: "IN-03", item_id: "B17", jurisdiction: "india", note: "construction debris — no rule stream, no fine asserted" },
  { case_id: "NY-01", item_id: "B01", jurisdiction: "nyc", note: "empty glass jar — recyclables, confident Tier 1" },
  { case_id: "NY-02", item_id: "B10", jurisdiction: "nyc", note: "residue-clogged takeout container — clarify" },
  { case_id: "NY-03", item_id: "B12", jurisdiction: "nyc", note: "empty dry paint can — recyclables per DSNY guidance" },
  { case_id: "GB-01", item_id: "B13", jurisdiction: "england", note: "grass clippings — garden stream Tier 1" },
  { case_id: "GB-02", item_id: "B11", jurisdiction: "england", note: "half-full takeaway cup — clarify" },
  { case_id: "GB-03", item_id: "B04", jurisdiction: "england", note: "cardboard box — paper-card fibre stream Tier 1" },
  { case_id: "IN-04", item_id: "B14", jurisdiction: "india", note: "used diaper — sanitary stream Tier 1 (divergent example)" },
  { case_id: "NY-04", item_id: "B14", jurisdiction: "nyc", note: "used diaper — residual/trash Tier 1 (divergent example)" },
  { case_id: "GB-04", item_id: "B14", jurisdiction: "england", note: "disposable nappy — residual Tier 1 (divergent example)" },
];

async function main(): Promise<number> {
  const bench = loadBenchmark();
  const output = {
    version: 1,
    source: "generated by scripts/generate-sample-gallery.ts via lib/matrix.ts adjudicate()",
    generated_at: new Date().toISOString(),
    cases: [] as unknown[],
  };
  for (const def of defs) {
    const item = bench.items.find((i) => i.id === def.item_id);
    if (!item) {
      console.error(`missing benchmark item ${def.item_id}`);
      process.exit(1);
    }
    const gt = item.ground_truth[def.jurisdiction];
    const verdict = await adjudicate({
      jurisdiction: def.jurisdiction,
      attributes: {
        object_class: item.perception_attrs.object_class,
        material_surface: item.perception_attrs.material_surface,
        contamination: item.perception_attrs.contamination,
        hazard_flags: item.perception_attrs.hazard_flags,
        stream: gt.stream,
        scope: gt.scope,
      },
      confidence: item.perception_attrs.confidence,
      generator_class: "wastelens-gallery",
      rule_version: "1.0",
    });
    output.cases.push({
      case_id: def.case_id,
      item_id: def.item_id,
      label: item.label,
      jurisdiction: def.jurisdiction,
      note: def.note,
      image: item.image.publicPath,
      verdict: {
        tier: verdict.tier,
        stream: verdict.stream,
        clause_id: verdict.clause_id,
        rule_text: verdict.rule_text,
        source_url: verdict.source_url,
        effective_date: verdict.effective_date,
        question: verdict.question,
        guidance: verdict.guidance,
      },
    });
  }
  fs.writeFileSync(OUT, JSON.stringify(output, null, 2) + "\n");
  console.log(`GALLERY wrote ${output.cases.length} cached verdict cases to ${OUT}`);
  return 0;
}

main().then((c) => process.exit(c));